version: '3.8'

services:
  stats-server:
    build: statistics/server
    image: statistics
    container_name: statistics
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
#    volumes:
#      - ./logs/stats-server:/app/logs # Логи stats-server сохраняются на хосте
#      - ./reports/stats-server:/app/reports # Отчеты stats-server сохраняются на хосте

  stats-db:
    image: postgres:16.1
    container_name: postgres-stat
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stat
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
#    volumes:
#      - ./data/stats-db:/var/lib/postgresql/data # Данные Postgres сохраняются на хосте

  ewm-service:
    build: service
    image: server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
      - STATISTICS_SERVER_URL=http://stats-server:9090
#    volumes:
#      - ./logs/ewm-service:/app/logs # Логи ewm-service сохраняются на хосте
#      - ./reports/ewm-service:/app/reports # Отчеты ewm-service сохраняются на хосте

  ewm-db:
    image: postgres:16.1
    container_name: postgres-main
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
#    volumes:
#      - ./data/ewm-db:/var/lib/postgresql/data # Данные Postgres сохраняются на хосте


