drop table if exists requests cascade;

drop table if exists events_compilations cascade;

drop table if exists events cascade;

drop table if exists users cascade;

drop table if exists categories cascade;

drop table if exists compilations cascade;

drop table if exists reactions cascade;

drop table if exists comments cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name  VARCHAR(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000)                 NOT NULL,
    category           BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    initiator          BIGINT REFERENCES users (id) ON DELETE CASCADE,
    description        VARCHAR(7000)                 NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    location_lat       VARCHAR(128)                  NOT NULL,
    location_lon       VARCHAR(128)                  NOT NULL,
    paid               BOOLEAN                       NOT NULL,
    participant_limit  INTEGER                       NOT NULL,
    request_moderation BOOLEAN                       NOT NULL,
    title              VARCHAR(120)                  NOT NULL,
    state              VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    confirmed_requests INTEGER     DEFAULT 0,
    views              BIGINT      DEFAULT 0
);

CREATE TABLE IF NOT EXISTS requests
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event     BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    status    VARCHAR(64) DEFAULT 'PENDING' NOT NULL

);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reactions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    reaction_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT unique_user_event_reaction_type UNIQUE (user_id, event_id, reaction_type)
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    text VARCHAR(2000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);